=== AMWA-TV/is-04/tags/v1.0/html-APIs/schemas/node.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes the Node and the services which run on it",
  "title": "Node resource",
  "required": [
    "id",
    "version",
    "label",
    "href",
    "caps",
    "services"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the Node",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "version": {
      "description": "String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed",
      "type": "string",
      "pattern": "^[0-9]+:[0-9]+$"
    },
    "label": {
      "description": "Freeform string label for the Node",
      "type": "string"
    },
    "href": {
      "description": "HTTP access href for the Node's API",
      "type": "string",
      "format": "uri"
    },
    "hostname": {
      "description": "Node hostname (optional)",
      "type": "string",
      "format": "hostname"
    },
    "caps": {
      "description": "Capabilities (not yet defined)",
      "type": "object"
    },
    "services": {
      "description": "Array of objects containing a URN format type and href",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["href", "type"],
        "properties": {
          "href": {
            "type": "string",
            "description": "URL to reach a service running on the Node",
            "format": "uri"
          },
          "type": {
            "type": "string",
            "description": "URN identifying the type of service",
            "format": "uri"
          }
        }
      }
    }
  }
}

=== AMWA-TV/is-04/examples/queryapi-v1.0-nodes-get-200.json
[
    {
        "version": "1441716120:318744030", 
        "hostname": "host1", 
        "label": "host1", 
        "href": "http://172.29.176.102:12345/", 
        "services": [
            {
                "href": "http://172.29.176.102:12345/x-manufacturer/status/", 
                "type": "urn:x-manufacturer:service:status"
            }, 
            {
                "href": "http://172.29.176.102:12345/x-manufacturer/pipelinemanager/", 
                "type": "urn:x-manufacturer:service:pipelinemanager"
            }, 
            {
                "href": "http://172.29.176.102:12345/x-manufacturer/mdnsbridge/", 
                "type": "urn:x-manufacturer:service:mdnsbridge"
            }
        ], 
        "caps": {}, 
        "id": "c8ba20e9-e197-4ec5-8764-4da672128589"
    }, 
    {
        "version": "1441716067:450064243", 
        "hostname": "host2", 
        "label": "host2", 
        "href": "http://172.29.176.19:12345/", 
        "services": [
            {
                "href": "http://172.29.176.19:12345/x-manufacturer/pipelinemanager/", 
                "type": "urn:x-manufacturer:service:pipelinemanager"
            }, 
            {
                "href": "http://172.29.176.19:12345/x-manufacturer/status/", 
                "type": "urn:x-manufacturer:service:status"
            }, 
            {
                "href": "http://172.29.176.19:12345/x-manufacturer/mdnsbridge/", 
                "type": "urn:x-manufacturer:service:mdnsbridge"
            }
        ], 
        "caps": {}, 
        "id": "cebc6305-e8db-4026-aeb5-eb7a5620839e"
    }
]

=== AMWA-TV/is-04/examples/nodeapi-v1.1-self-get-200.json
{
    "version": "1441700172:318426300", 
    "hostname": "host1", 
    "caps": {}, 
    "href": "http://172.29.80.65:12345/", 
    "services": [
        {
            "href": "http://172.29.80.65:12345/x-manufacturer/pipelinemanager/", 
            "type": "urn:x-manufacturer:service:pipelinemanager"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-manufacturer/status/", 
            "type": "urn:x-manufacturer:service:status"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-manufacturer/tally/", 
            "type": "urn:x-manufacturer:service:tally"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-manufacturer/mdnsbridge/", 
            "type": "urn:x-manufacturer:service:mdnsbridge"
        }, 
        {
            "href": "http://172.29.80.65:12345/x-manufacturer/storequery/", 
            "type": "urn:x-manufacturer:service:storequery"
        }
    ], 
    "label": "host1", 
    "id": "3b8be755-08ff-452b-b217-c9151eb21193"
}
